# try-catch-finally 보다는 try-with-resources를 사용하라.

### try-with-resources??

자바8 버전부터 try-with-resources 구문이 추가되었는데 이는 try가 종료될 때 자동으로 자원을 해제해주는 기능이다.

### try-catch-finally

```java
MyResource myResource =new MyResource(); // AutoCloseable 상속
try{
    myResource.doSomething();
}finally{
    myResource.close();
}
```

try-catch-finally 구문을 사용하면 위 코드처럼 finally 구문에서 자원을 닫아줘야한다. 위 코드만 봤을 때는 그렇게 큰 문제처럼 느껴지지 않는다. 근데 try 구문 내부에서 자원 하나를 더 생성한다면?

```java
    try{
            myResource.doSomething();
            MyResource myResource1 = null;
            try {
                /*
                * 실행해야할 메서드...
                * */
                myResource1 = new MyResource();
                myResource1.doSomething();
            } finally {
                if (myResource1 != null) { // 인스턴스 생성 전에 오류가 날 수도 있기에
                    myResource1.close();
                }
            }
        }finally {
            myResource.close();
        }
```

위 처럼 코드가 굉장히 복잡해지고 장황해진다.

## try-with-resources 사용하기

```java
try(MyResource myResource =new MyResource();
    MyResource myResource1 =new MyResource()) {
    myResource.doSomething();
    myResource1.doSomething();
}
```

코드가 굉장히 간결해졌고 try 구문 실행이 종료되면 내부에 선언한 변수들에 대한 해제가 진행된다. 또한 catch 절도 당연히 사용할 수 있다.
